"""checkbox list

Revision ID: 503169cbe883
Revises: ec2e140877e5
Create Date: 2020-06-02 23:30:48.248676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503169cbe883'
down_revision = 'ec2e140877e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
